### ISSUE TITLE
ONTrack for influenza 

### ISSUE THREAD

**Issue by leocaserta** [MaestSi/ONTrack2#1]
Hello,
I tested ONTrack for amplicon sequencing of some viruses and it worked, however, I tested for influenza and it generated only one of the 8 segments. I guess this may have happened because the size of the segments are different and the number of reads per segment is also different. Basically, I use the same pair of primers to amplify segments ranging from 900 to 2000bp. Is there any parameter that I should be using in order to obtain contigs for all segments? 

Thank you 

Leonardo

**Comment by MaestSi** [comment]
Ciao,
ONTrack2 only supports the generation of one consensus sequence for each sample. In case you have multiple amplicons generated with the same primer pair (if I understood correctly) you should probably just perform a de novo assembly, with tools like Flye or Canu. In alternative, if each segment has a different size, you could split the fastq file by read length, so that reads from each of the 8 segments are saved to 8 different fastq files, and run ONTrack2 on each file separately.
For example, you may convert your fastq file (sample.fastq) to fasta with:
`seqtk seq -A sample.fastq > sample.fasta`
then save this script to file Plot_read_length.R (it requires R with Biostrings package installed)
```
args = commandArgs(trailingOnly=TRUE)

if (length(args) == 1) {
  input_dir <- args[1]
} else if (length(args) == 3) {
  input_dir <- args[1]
  lb <- args[2]
  ub <- args[3]
} else {
  stop("At least one argument (input_dir) must be supplied\n")
}

#load BioStrings package
suppressMessages(library(Biostrings))

reads_files <- list.files(input_dir, pattern = "fasta", full.names = TRUE)

pdf(paste0(input_dir, "/hist_read_length_", basename(input_dir), ".pdf"))
par(mfrow = c(2, 2))
for (i in 1:length(reads_files)) {
  sequences <- readDNAStringSet(reads_files[i], "fasta")
  ws <- width(sequences)
  if (length(args) == 1) {
    lb <- min(ws)
    ub <- max(ws)
  } else {
    lb <- as.double(lb)
    ub <- as.double(ub)
  }

  read_length <- ws[which(ws > lb & ws < ub)]
  sample_name_tmp <- gsub("\\.fasta", "", basename(reads_files[i]))
  sample_name <- gsub("_pass_trimmed", "", sample_name_tmp)
  logfile=paste0(input_dir, "/logfile_do_hist_", sample_name, ".txt")
  hist(read_length, main = sample_name, breaks = 100, col = "blue", xlab = "Read length", ylab = "Number of reads", xlim = c(lb, ub))
  cat(text = paste0("Mean read length (stdev): ", sprintf("%.0f", mean(ws)), " (", sprintf("%.0f", sd(ws)), ")"), file = logfile, sep = "\n", append = TRUE)
}
dev.off()
```
and produce a read lengths histogram with:
`Rscript Plot_read_length.R sample.fasta`
After visual inspection of the histogram, you should be able to identify read length cut-offs for sorting out the different amplicons and split the reads with:
`cat sample.fastq | NanoFilt -l <min length> --maxlength <max length> > sample_ampliconX.fastq`
Best,
Simone

**Comment by leocaserta** [comment]
Ciao Simone, 
Thank you so much, I will test your suggestion. 

Leonardo

**Comment by MaestSi** [comment]
Ciao Leonardo,
I'm going to close this issue. In case you have any further questions, feel free to reopen it.
Best,
SM
